const $=s=>document.querySelector(s);let data=[],currentFilter="all";
function symbols(){return [...new Set($("#symbols").value.split(/[\n,\s]+/).map(x=>x.trim()).filter(Boolean))]}
function fmt(n){return n==null||Number.isNaN(Number(n))?"داده در دسترس نیست":new Intl.NumberFormat("fa-IR").format(n)}
function money(n){if(n==null)return"داده در دسترس نیست";n=Number(n);if(n>=1e12)return(n/1e12).toLocaleString("fa-IR",{maximumFractionDigits:2})+" همت";if(n>=1e9)return(n/1e9).toLocaleString("fa-IR",{maximumFractionDigits:2})+" میلیارد";if(n>=1e6)return(n/1e6).toLocaleString("fa-IR",{maximumFractionDigits:2})+" میلیون";return fmt(n)}
function renderTags(){$("#tags").innerHTML=symbols().map(s=>`<span class="tag">${s}<button data-remove="${s}">×</button></span>`).join("");document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{$("#symbols").value=symbols().filter(x=>x!==b.dataset.remove).join("\n");renderTags()})}
$("#symbols").addEventListener("input",renderTags);
function renderSummary(s){$("#summary").innerHTML=[["تعداد نمادها",`${s.count} نماد`],["بیشترین ارزش معاملات",money(s.top_trade_value)],["نماد برتر",s.top_symbol||"—"],["تعداد صف خرید",s.buy_queue],["تعداد صف فروش",s.sell_queue],["قابل معامله",s.tradable]].map(x=>`<div class="card"><div class="k">${x[0]}</div><div class="v">${x[1]}</div></div>`).join("")}
function filtered(){return data.filter(r=>currentFilter==="all"?true:currentFilter==="positive"?Number(r.change_percent)>0:currentFilter==="negative"?Number(r.change_percent)<0:currentFilter==="money_in"?Number(r.money_flow)>0:currentFilter==="money_out"?Number(r.money_flow)<0:r.status===currentFilter)}
function renderTable(){$("#rows").innerHTML=filtered().map(r=>{let ch=r.change_percent,flow=r.money_flow;return`<tr><td>${r.rank}</td><td><b>${r.symbol}</b></td><td>${fmt(r.last_price)}</td><td class="${ch>0?"pos":ch<0?"neg":""}">${ch==null?"داده در دسترس نیست":Number(ch).toFixed(2)+"%"}</td><td>${fmt(r.volume)}</td><td>${money(r.trade_value)}</td><td class="${flow>0?"pos":flow<0?"neg":""}">${flow==null?"داده در دسترس نیست":money(flow)}</td><td>${r.status_text||"داده در دسترس نیست"}</td><td>${r.status==="buy_queue"?"امکان خرید عادی وجود ندارد":r.status==="sell_queue"?"صف فروش":r.status==="normal"?"قابل معامله":"نامشخص"}</td><td>${r.analysis_score==null?"—":r.analysis_score+"/100"}</td><td><button data-star="${r.symbol}">⭐</button></td></tr>`}).join("");document.querySelectorAll("[data-star]").forEach(b=>b.onclick=async()=>{await fetch("/api/watchlist/"+encodeURIComponent(b.dataset.star),{method:"POST"});b.textContent="✓"})}
function renderAnalysis(){$("#analysis").innerHTML=filtered().map(r=>`<article class="analysis-card"><h3>${r.symbol} — تحلیل هوشمند</h3><div class="score">${r.analysis_score==null?"امتیاز: داده کافی نیست":"امتیاز: "+r.analysis_score+" / 100"}</div><ul>${(r.analysis||["داده در دسترس نیست"]).map(x=>`<li>${x}</li>`).join("")}</ul><details><summary>جزئیات فرمول امتیاز</summary><p>فقط عوامل دارای داده استفاده می‌شوند و وزن‌ها مجدداً نرمال می‌شوند.</p><ul>${(r.score_factors||[]).map(f=>`<li>${f.name}: وزن ${f.weight}% — ${f.value==null?"داده در دسترس نیست":f.value}</li>`).join("")}</ul></details></article>`).join("")}
function err(x){$("#error").textContent=x;$("#error").classList.remove("hidden")}
async function run(url="/api/analyze"){if(!symbols().length)return err("حداقل یک نماد وارد کنید.");$("#loading").classList.remove("hidden");$("#error").classList.add("hidden");try{let res=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbols:symbols()})});let out=await res.json();if(!res.ok)throw Error(out.detail||"خطا");data=out.items||[];renderSummary(out.summary);renderTable();renderAnalysis();$("#updated").textContent="آخرین بروزرسانی: "+new Date().toLocaleTimeString("fa-IR")}catch(e){err(e.message)}finally{$("#loading").classList.add("hidden")}}
$("#analyze").onclick=()=>run();$("#refresh").onclick=()=>run("/api/refresh");$("#clear").onclick=()=>{$("#symbols").value="";data=[];renderTags();$("#summary").innerHTML="";$("#rows").innerHTML="";$("#analysis").innerHTML=""};document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");currentFilter=b.dataset.filter;renderTable();renderAnalysis()});renderTags();
